import os
import sys

# --- Environment setup (must happen before any PyQt6 import) ---
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

# --- Cross-platform ctypes.windll injection ---
# On non-Windows platforms, `ctypes.windll` does not exist. Many tests use
# `patch("ctypes.windll.shell32.IsUserAnAdmin", ..., create=True)` which
# traverses the path `ctypes.windll.shell32`. Even with `create=True`, the
# intermediate `ctypes.windll` must exist for patch to resolve the path.
# Inject a MagicMock here so those patches work on Linux/macOS CI.
if sys.platform != "win32":
    import ctypes
    from unittest.mock import MagicMock

    if not hasattr(ctypes, "windll"):
        ctypes.windll = MagicMock()  # type: ignore[attr-defined]

import pytest
import numpy as np
from multiprocessing import shared_memory
from gesture_controller.models.data_types import Hand, Landmark3D

failed_reports = []
collected_warnings = []


def pytest_runtest_logreport(report) -> None:
    """Collect failed test reports."""
    if report.when in ("setup", "call", "teardown"):
        if report.failed:
            failed_reports.append(report)


def pytest_warning_recorded(warning_message, when, nodeid, location) -> None:
    """Collect warnings recorded during test runs."""
    collected_warnings.append(
        {
            "message": str(warning_message.message),
            "category": (
                warning_message.category.__name__ if warning_message.category else "Warning"
            ),
            "filename": warning_message.filename,
            "lineno": warning_message.lineno,
            "when": when,
            "nodeid": nodeid,
        }
    )


def pytest_configure(config) -> None:
    """Configure settings if needed."""
    pass


def pytest_unconfigure(config) -> None:
    """Generate the structured error_log.md file at the end of the test run (Sprint 4 Sidestep)."""
    from pathlib import Path

    log_path = Path(config.rootdir) / "error_log.md"

    try:
        with open(log_path, "w", encoding="utf-8") as f:
            f.write("# Maestro Test Execution Error & Warning Log\n\n")
            f.write(
                "This file is automatically generated by pytest hooks to assist coding agents in iterative improvement.\n\n"
            )

            if not failed_reports and not collected_warnings:
                f.write("## ✅ All Tests Passed\n\n")
                f.write(
                    "No failures, errors, or warnings were encountered during this test execution run.\n"
                )
                return

            if failed_reports:
                f.write("## ❌ Test Failures\n\n")
                for report in failed_reports:
                    f.write(f"### Test: `{report.nodeid}`\n")
                    f.write(f"- **Outcome**: {report.outcome}\n")
                    f.write(f"- **Phase**: {report.when}\n\n")
                    f.write("#### Traceback & Error Details:\n")
                    f.write("```text\n")
                    f.write(str(report.longrepr) + "\n")
                    f.write("```\n\n")

                    if hasattr(report, "capstdout") and report.capstdout:
                        f.write("#### Captured Stdout:\n")
                        f.write("```text\n")
                        f.write(report.capstdout + "\n")
                        f.write("```\n\n")
                    if hasattr(report, "capstderr") and report.capstderr:
                        f.write("#### Captured Stderr:\n")
                        f.write("```text\n")
                        f.write(report.capstderr + "\n")
                        f.write("```\n\n")
                    f.write("---\n\n")

            if collected_warnings:
                f.write("## ⚠️ Pytest Warnings\n\n")
                for w in collected_warnings:
                    f.write(f"- **Category**: `{w['category']}`\n")
                    f.write(f"  - **Message**: {w['message']}\n")
                    f.write(f"  - **Location**: `{w['filename']}:{w['lineno']}`\n")
                    if w["nodeid"]:
                        f.write(f"  - **Node ID**: `{w['nodeid']}`\n")
                    f.write("\n")
    except Exception as e:
        print(f"Failed to generate error_log.md: {e}")


def make_hand(landmarks: list[tuple[float, float, float]], handedness: str = "Right") -> Hand:
    """Helper to construct a Hand object from coordinate tuples."""
    lms = tuple(Landmark3D(x=x, y=y, z=z) for x, y, z in landmarks)
    return Hand(landmarks=lms, handedness=handedness, confidence=1.0)


@pytest.fixture(autouse=True)
def control_gc(request):
    """Automatically disable garbage collection for property-based tests to avoid Python 3.14 GC crashes (S4-4)."""
    import gc

    is_prop_test = "test_property_based" in request.node.nodeid
    if is_prop_test:
        gc.disable()
    yield
    if is_prop_test:
        gc.enable()


@pytest.fixture
def open_palm_hand() -> Hand:
    """Hand with all 5 fingers extended, facing camera."""
    coords = [
        (0.5, 0.8, 0.0),  # 0: WRIST
        (0.45, 0.65, 0.0),  # 1: THUMB_CMC
        (0.4, 0.5, 0.0),  # 2: THUMB_MCP
        (0.37, 0.4, 0.0),  # 3: THUMB_IP
        (0.35, 0.3, 0.0),  # 4: THUMB_TIP
        (0.42, 0.55, 0.0),  # 5: INDEX_MCP
        (0.4, 0.4, 0.0),  # 6: INDEX_PIP
        (0.39, 0.3, 0.0),  # 7: INDEX_DIP
        (0.38, 0.22, 0.0),  # 8: INDEX_TIP
        (0.5, 0.53, 0.0),  # 9: MIDDLE_MCP
        (0.5, 0.38, 0.0),  # 10: MIDDLE_PIP
        (0.5, 0.28, 0.0),  # 11: MIDDLE_DIP
        (0.5, 0.2, 0.0),  # 12: MIDDLE_TIP
        (0.57, 0.55, 0.0),  # 13: RING_MCP
        (0.58, 0.42, 0.0),  # 14: RING_PIP
        (0.58, 0.33, 0.0),  # 15: RING_DIP
        (0.58, 0.26, 0.0),  # 16: RING_TIP
        (0.63, 0.58, 0.0),  # 17: PINKY_MCP
        (0.64, 0.47, 0.0),  # 18: PINKY_PIP
        (0.64, 0.39, 0.0),  # 19: PINKY_DIP
        (0.65, 0.33, 0.0),  # 20: PINKY_TIP
    ]
    return make_hand(coords)


@pytest.fixture
def pointing_hand() -> Hand:
    """Index finger extended, all others curled."""
    coords = [
        (0.5, 0.8, 0.0),  # 0: WRIST
        (0.45, 0.65, -0.02),  # 1: THUMB_CMC
        (0.47, 0.7, -0.01),  # 2: THUMB_MCP
        (0.48, 0.73, -0.01),  # 3: THUMB_IP
        (0.47, 0.7, -0.01),  # 4: THUMB_TIP
        (0.44, 0.6, 0.0),  # 5: INDEX_MCP
        (0.43, 0.45, 0.0),  # 6: INDEX_PIP
        (0.42, 0.33, 0.0),  # 7: INDEX_DIP
        (0.41, 0.22, 0.0),  # 8: INDEX_TIP
        (0.5, 0.62, 0.0),  # 9: MIDDLE_MCP
        (0.51, 0.68, 0.0),  # 10: MIDDLE_PIP
        (0.51, 0.72, 0.0),  # 11: MIDDLE_DIP
        (0.50, 0.7, 0.0),  # 12: MIDDLE_TIP
        (0.55, 0.63, 0.0),  # 13: RING_MCP
        (0.56, 0.68, 0.0),  # 14: RING_PIP
        (0.56, 0.72, 0.0),  # 15: RING_DIP
        (0.55, 0.7, 0.0),  # 16: RING_TIP
        (0.59, 0.64, 0.0),  # 17: PINKY_MCP
        (0.60, 0.68, 0.0),  # 18: PINKY_PIP
        (0.60, 0.71, 0.0),  # 19: PINKY_DIP
        (0.59, 0.69, 0.0),  # 20: PINKY_TIP
    ]
    return make_hand(coords)


@pytest.fixture
def fist_hand() -> Hand:
    """All fingers curled (closed fist)."""
    coords = [
        (0.5, 0.8, 0.0),
        (0.45, 0.68, -0.03),
        (0.47, 0.72, -0.02),
        (0.48, 0.74, -0.02),
        (0.47, 0.72, -0.02),
        (0.46, 0.68, 0.0),
        (0.47, 0.72, 0.0),
        (0.47, 0.74, 0.0),
        (0.46, 0.72, 0.0),
        (0.50, 0.68, 0.0),
        (0.50, 0.72, 0.0),
        (0.50, 0.74, 0.0),
        (0.50, 0.72, 0.0),
        (0.53, 0.68, 0.0),
        (0.54, 0.72, 0.0),
        (0.54, 0.74, 0.0),
        (0.53, 0.72, 0.0),
        (0.56, 0.69, 0.0),
        (0.57, 0.72, 0.0),
        (0.57, 0.74, 0.0),
        (0.56, 0.72, 0.0),
    ]
    return make_hand(coords)


@pytest.fixture
def pinch_hand() -> Hand:
    """Thumb and index tips close together, others extended."""
    coords = [
        (0.5, 0.8, 0.0),
        (0.45, 0.65, -0.02),
        (0.42, 0.5, -0.02),
        (0.40, 0.38, -0.02),
        (0.39, 0.32, -0.02),
        (0.44, 0.6, 0.0),
        (0.42, 0.45, 0.0),
        (0.41, 0.35, 0.0),
        (0.40, 0.32, 0.0),
        (0.5, 0.58, 0.0),
        (0.5, 0.43, 0.0),
        (0.5, 0.32, 0.0),
        (0.5, 0.24, 0.0),
        (0.56, 0.59, 0.0),
        (0.57, 0.46, 0.0),
        (0.57, 0.36, 0.0),
        (0.57, 0.28, 0.0),
        (0.60, 0.61, 0.0),
        (0.61, 0.50, 0.0),
        (0.61, 0.42, 0.0),
        (0.61, 0.36, 0.0),
    ]
    return make_hand(coords)


@pytest.fixture
def thumbs_up_hand() -> Hand:
    """Thumb extended up, all others curled."""
    coords = [
        (0.5, 0.8, 0.0),
        (0.42, 0.65, -0.04),
        (0.35, 0.50, -0.04),
        (0.30, 0.38, -0.04),
        (0.27, 0.28, -0.04),
        (0.46, 0.68, 0.0),
        (0.47, 0.72, 0.0),
        (0.47, 0.74, 0.0),
        (0.46, 0.72, 0.0),
        (0.50, 0.68, 0.0),
        (0.50, 0.72, 0.0),
        (0.50, 0.74, 0.0),
        (0.50, 0.72, 0.0),
        (0.53, 0.68, 0.0),
        (0.54, 0.72, 0.0),
        (0.54, 0.74, 0.0),
        (0.53, 0.72, 0.0),
        (0.56, 0.69, 0.0),
        (0.57, 0.72, 0.0),
        (0.57, 0.74, 0.0),
        (0.56, 0.72, 0.0),
    ]
    return make_hand(coords)


@pytest.fixture
def shared_memory_frame() -> tuple[shared_memory.SharedMemory, np.ndarray]:
    """Provides a shared memory segment populated with a dummy frame."""
    import struct
    from gesture_controller.vision.double_buffer import TOTAL_SIZE, HEADER_SIZE

    shm = shared_memory.SharedMemory(create=True, size=TOTAL_SIZE)
    # Initialize sequence counter to 2 (slot 0 complete)
    struct.pack_into("<Q", shm.buf, 0, 2)
    frame = np.ndarray((480, 640, 3), dtype=np.uint8, buffer=shm.buf, offset=HEADER_SIZE)
    frame.fill(0)
    yield shm, frame
    shm.close()
    shm.unlink()


@pytest.fixture(scope="session")
def qapp() -> "QApplication":
    """Provide a session-scoped QApplication instance for all GUI tests."""
    import sys
    from PyQt6.QtWidgets import QApplication

    app = QApplication.instance()
    if app is None:
        app = QApplication(sys.argv)
    yield app
    app.processEvents()
